import setlog from "./script/setlog";
import parseApiDetails from "./script/parseApiDetails";

export function handleParse(htmlText) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlText, 'text/html');
  if (!parser) {
    setlog("parseFromString转换", '异常，浏览器不支持DOMParser API，请切换浏览器重试', 'handleParse:8')
    return []
  }
  setlog("提取待转化表格", '开始', 'handleParse:11')
  // 最顶层的控制表格生成数量--表格的展开
  const tablesEl = doc.querySelectorAll('.wrapper > .block .opblock-tag-section.is-open')
  if (tablesEl.length === 0) {
    setlog("提取待转化表格", `异常，未提取到数据，请检查数据源是否包含，检测是否数据源问题：打开Swagger网页的控制台然后运行以下代码【document.querySelectorAll('.wrapper > .block .opblock-tag-section.is-open');】检查是否有元素数组，若没有，则是后端接口文档问题。`, 'handleParse:15')
    return []
  }
  const tables = [];
  tablesEl.forEach(({ innerHTML }) => {
    // setlog("提取待转化表格", '', 'parseApiDetails:25')
    const table = parseApiDetails(innerHTML);
    tables.push(table);
  })
  return tables;
}
// 示例 HTML 文本
// const htmlText = `
// <div class="wrapper"><section class="block col-12 block-desktop col-12-desktop"><div><span><div class="opblock-tag-section"><h4 class="opblock-tag" id="operations-tag-任务管理" data-tag="任务管理" data-is-open="false"><a class="nostyle" href="#/任务管理"><span>任务管理</span></a><small><div class="markdown"><p>Task Controller</p>
// </div></small><div></div><button class="expand-operation" title="Expand operation"><svg class="arrow" width="20" height="20"><use href="#large-arrow" xlink:href="#large-arrow"></use></svg></button></h4><noscript></noscript></div></span><span><div class="opblock-tag-section is-open"><h4 class="opblock-tag" id="operations-tag-指标体系管理" data-tag="指标体系管理" data-is-open="true"><a class="nostyle" href="#/指标体系管理"><span>指标体系管理</span></a><small><div class="markdown"><p>Form Entry Controller</p>
// </div></small><div></div><button class="expand-operation" title="Collapse operation"><svg class="arrow" width="20" height="20"><use href="#large-arrow-down" xlink:href="#large-arrow-down"></use></svg></button></h4><div class="no-margin"><!-- react-text: 27610 --> <!-- /react-text --><span><div class="opblock opblock-get is-open" id="operations-指标体系管理-getAllFormEntryUsingGET"><div class="opblock-summary opblock-summary-get"><span class="opblock-summary-method">GET</span><span class="opblock-summary-path" data-path="/api/form_entry"><a class="nostyle" href="#/指标体系管理/getAllFormEntryUsingGET"><span>​/api​/form_entry</span></a></span><div class="opblock-summary-description">获取指标体系列表</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 27622 --></div><div class="no-margin"><!-- react-text: 30941 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>获取指标体系列表</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="key" data-param-in="query"><td class="parameters-col_name"><div class="parameter__name"><!-- react-text: 30963 -->key<!-- /react-text --></div><div class="parameter__type"><!-- react-text: 30965 -->string<!-- /react-text --></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30968 -->(<!-- /react-text --><!-- react-text: 30969 -->query<!-- /react-text --><!-- react-text: 30970 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>关键词搜索</p>
// </div><input type="text" class="" title="" placeholder="key - 关键词搜索" disabled="" value=""></td></tr><tr data-param-name="page_num" data-param-in="query"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30977 -->page_num<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30980 -->integer<!-- /react-text --><span class="prop-format"><!-- react-text: 30982 -->($<!-- /react-text --><!-- react-text: 30983 -->int32<!-- /react-text --><!-- react-text: 30984 -->)<!-- /react-text --></span></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30987 -->(<!-- /react-text --><!-- react-text: 30988 -->query<!-- /react-text --><!-- react-text: 30989 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>当前页码</p>
// </div><input type="text" class="" title="" placeholder="page_num - 当前页码" disabled="" value="1"></td></tr><tr data-param-name="page_size" data-param-in="query"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30996 -->page_size<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30999 -->integer<!-- /react-text --><span class="prop-format"><!-- react-text: 31001 -->($<!-- /react-text --><!-- react-text: 31002 -->int32<!-- /react-text --><!-- react-text: 31003 -->)<!-- /react-text --></span></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 31006 -->(<!-- /react-text --><!-- react-text: 31007 -->query<!-- /react-text --><!-- react-text: 31008 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>每页条数</p>
// </div><input type="text" class="" title="" placeholder="page_size - 每页条数" disabled="" value="10"></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 31058 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-post is-open" id="operations-指标体系管理-createFormEntryUsingPOST"><div class="opblock-summary opblock-summary-post"><span class="opblock-summary-method">POST</span><span class="opblock-summary-path" data-path="/api/form_entry"><a class="nostyle" href="#/指标体系管理/createFormEntryUsingPOST"><span>​/api​/form_entry</span></a></span><div class="opblock-summary-description">新建指标体系列表</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 27635 --></div><div class="no-margin"><!-- react-text: 30838 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>新建指标体系列表</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="formEntry" data-param-in="body"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30860 -->formEntry<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30863 -->object<!-- /react-text --></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30866 -->(<!-- /react-text --><!-- react-text: 30867 -->body<!-- /react-text --><!-- react-text: 30868 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>formEntry</p>
// </div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div class="body-param" data-param-name="formEntry" data-param-in="body"><div class="highlight-code"><pre class="body-param__example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"formBody"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="token-not-formatted">
//     </span><span class="token-string">"targets"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">[</span><span class="token-not-formatted">
//       </span><span class="">{</span><span class="token-not-formatted">
//         </span><span class="token-string">"children"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">[</span><span class="token-not-formatted">
//           </span><span class="">null</span><span class="token-not-formatted">
//         </span><span class="">]</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"description"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"name"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"result"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"score"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"type"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="token-not-formatted">
//       </span><span class="">}</span><span class="token-not-formatted">
//     </span><span class="">]</span><span class="token-not-formatted">
//   </span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"formName"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div><div class="body-param-options"><label for=""><span>Parameter content type</span><div class="content-type-wrapper body-param-content-type"><select class="content-type"><option value="application/json">application/json</option></select></div></label></div></div></div></div></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="201"><td class="response-col_status">201</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Created</p>
// </div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30937 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-get is-open" id="operations-指标体系管理-getFormEntryByIdUsingGET"><div class="opblock-summary opblock-summary-get"><span class="opblock-summary-method">GET</span><span class="opblock-summary-path" data-path="/api/form_entry/{id}"><a class="nostyle" href="#/指标体系管理/getFormEntryByIdUsingGET"><span>​/api​/form_entry​/{id}</span></a></span><div class="opblock-summary-description">获取指标体系列表</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 27648 --></div><div class="no-margin"><!-- react-text: 30752 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>获取指标体系列表</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="id" data-param-in="path"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30774 -->id<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30777 -->integer<!-- /react-text --><span class="prop-format"><!-- react-text: 30779 -->($<!-- /react-text --><!-- react-text: 30780 -->int32<!-- /react-text --><!-- react-text: 30781 -->)<!-- /react-text --></span></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30784 -->(<!-- /react-text --><!-- react-text: 30785 -->path<!-- /react-text --><!-- react-text: 30786 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>id</p>
// </div><input type="text" class="" title="" placeholder="id - id" disabled="" value=""></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30836 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-put is-open" id="operations-指标体系管理-updateFormEntryUsingPUT"><div class="opblock-summary opblock-summary-put"><span class="opblock-summary-method">PUT</span><span class="opblock-summary-path" data-path="/api/form_entry/{id}"><a class="nostyle" href="#/指标体系管理/updateFormEntryUsingPUT"><span>​/api​/form_entry​/{id}</span></a></span><div class="opblock-summary-description">更新指标体系</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 27661 --></div><div class="no-margin"><!-- react-text: 30633 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="formEntry" data-param-in="body"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30652 -->formEntry<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30655 -->object<!-- /react-text --></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30658 -->(<!-- /react-text --><!-- react-text: 30659 -->body<!-- /react-text --><!-- react-text: 30660 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>formEntry</p>
// </div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div class="body-param" data-param-name="formEntry" data-param-in="body"><div class="highlight-code"><pre class="body-param__example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"formBody"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="token-not-formatted">
//     </span><span class="token-string">"targets"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">[</span><span class="token-not-formatted">
//       </span><span class="">{</span><span class="token-not-formatted">
//         </span><span class="token-string">"children"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">[</span><span class="token-not-formatted">
//           </span><span class="">null</span><span class="token-not-formatted">
//         </span><span class="">]</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"description"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"name"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"result"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"score"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//         </span><span class="token-string">"type"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="token-not-formatted">
//       </span><span class="">}</span><span class="token-not-formatted">
//     </span><span class="">]</span><span class="token-not-formatted">
//   </span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"formName"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div><div class="body-param-options"><label for=""><span>Parameter content type</span><div class="content-type-wrapper body-param-content-type"><select class="content-type"><option value="application/json">application/json</option></select></div></label></div></div></div></div></td></tr><tr data-param-name="id" data-param-in="path"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30681 -->id<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30684 -->integer<!-- /react-text --><span class="prop-format"><!-- react-text: 30686 -->($<!-- /react-text --><!-- react-text: 30687 -->int32<!-- /react-text --><!-- react-text: 30688 -->)<!-- /react-text --></span></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30691 -->(<!-- /react-text --><!-- react-text: 30692 -->path<!-- /react-text --><!-- react-text: 30693 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>id</p>
// </div><input type="text" class="" title="" placeholder="id - id" disabled="" value=""></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="201"><td class="response-col_status">201</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Created</p>
// </div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30748 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-delete is-open" id="operations-指标体系管理-delFormEntryUsingDELETE"><div class="opblock-summary opblock-summary-delete"><span class="opblock-summary-method">DELETE</span><span class="opblock-summary-path" data-path="/api/form_entry/{id}"><a class="nostyle" href="#/指标体系管理/delFormEntryUsingDELETE"><span>​/api​/form_entry​/{id}</span></a></span><div class="opblock-summary-description">根据id删除指标体系列表</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 27674 --></div><div class="no-margin"><!-- react-text: 30547 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>根据id删除指标体系列表</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="id" data-param-in="path"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30569 -->id<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30572 -->integer<!-- /react-text --><span class="prop-format"><!-- react-text: 30574 -->($<!-- /react-text --><!-- react-text: 30575 -->int32<!-- /react-text --><!-- react-text: 30576 -->)<!-- /react-text --></span></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30579 -->(<!-- /react-text --><!-- react-text: 30580 -->path<!-- /react-text --><!-- react-text: 30581 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>id</p>
// </div><input type="text" class="" title="" placeholder="id - id" disabled="" value=""></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="204"><td class="response-col_status">204</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>No Content</p>
// </div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30631 --> <!-- /react-text --></div></div></span><!-- react-text: 27761 --> <!-- /react-text --></div></div></span><span><div class="opblock-tag-section is-open"><h4 class="opblock-tag" id="operations-tag-用户" data-tag="用户" data-is-open="true"><a class="nostyle" href="#/用户"><span>用户</span></a><small><div class="markdown"><p>User Controller</p>
// </div></small><div></div><button class="expand-operation" title="Collapse operation"><svg class="arrow" width="20" height="20"><use href="#large-arrow-down" xlink:href="#large-arrow-down"></use></svg></button></h4><div class="no-margin"><!-- react-text: 24947 --> <!-- /react-text --><span><div class="opblock opblock-put is-open" id="operations-用户-createUserUsingPUT"><div class="opblock-summary opblock-summary-put"><span class="opblock-summary-method">PUT</span><span class="opblock-summary-path" data-path="/api/user"><a class="nostyle" href="#/用户/createUserUsingPUT"><span>​/api​/user</span></a></span><div class="opblock-summary-description">修改信息</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 24959 --></div><div class="no-margin"><!-- react-text: 30444 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>更新用户的信息</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="user" data-param-in="body"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30466 -->user<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30469 -->object<!-- /react-text --></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30472 -->(<!-- /react-text --><!-- react-text: 30473 -->body<!-- /react-text --><!-- react-text: 30474 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>user</p>
// </div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div class="body-param" data-param-name="user" data-param-in="body"><div class="highlight-code"><pre class="body-param__example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"fullname"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"new_password"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"password"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"roleId"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"username"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div><div class="body-param-options"><label for=""><span>Parameter content type</span><div class="content-type-wrapper body-param-content-type"><select class="content-type"><option value="application/json">application/json</option></select></div></label></div></div></div></div></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="201"><td class="response-col_status">201</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Created</p>
// </div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30543 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-patch is-open" id="operations-用户-updateAvatarUsingPATCH"><div class="opblock-summary opblock-summary-patch"><span class="opblock-summary-method">PATCH</span><span class="opblock-summary-path" data-path="/api/user/avatar"><a class="nostyle" href="#/用户/updateAvatarUsingPATCH"><span>​/api​/user​/avatar</span></a></span><div class="opblock-summary-description">修改用户头像</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 24972 --></div><div class="no-margin"><!-- react-text: 30342 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>修改用户头像</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="avatar" data-param-in="body"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30364 -->avatar<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30367 -->string<!-- /react-text --><span class="prop-format"><!-- react-text: 30369 -->($<!-- /react-text --><!-- react-text: 30370 -->binary<!-- /react-text --><!-- react-text: 30371 -->)<!-- /react-text --></span></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30374 -->(<!-- /react-text --><!-- react-text: 30375 -->body<!-- /react-text --><!-- react-text: 30376 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>avatar</p>
// </div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div class="body-param" data-param-name="avatar" data-param-in="body"><div class="highlight-code"><pre class="body-param__example microlight"><span class="">string</span></pre></div><div class="body-param-options"><label for=""><span>Parameter content type</span><div class="content-type-wrapper body-param-content-type"><select class="content-type"><option value="multipart/form-data">multipart/form-data</option></select></div></label></div></div></div></div></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="204"><td class="response-col_status">204</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>No Content</p>
// </div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30440 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-post is-open" id="operations-用户-loginUsingPOST"><div class="opblock-summary opblock-summary-post"><span class="opblock-summary-method">POST</span><span class="opblock-summary-path" data-path="/api/user/login"><a class="nostyle" href="#/用户/loginUsingPOST"><span>​/api​/user​/login</span></a></span><div class="opblock-summary-description">用户登录</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 24985 --></div><div class="no-margin"><!-- react-text: 30239 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-description-wrapper"><div class="opblock-description"><div class="markdown"><p>通过用户名和密码进行登录</p>
// </div></div></div><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="table-container"><table class="parameters"><thead><tr><th class="col_header parameters-col_name">Name</th><th class="col_header parameters-col_description">Description</th></tr></thead><tbody><tr data-param-name="request" data-param-in="body"><td class="parameters-col_name"><div class="parameter__name required"><!-- react-text: 30261 -->request<!-- /react-text --><span>&nbsp;*</span></div><div class="parameter__type"><!-- react-text: 30264 -->object<!-- /react-text --></div><div class="parameter__deprecated"></div><div class="parameter__in"><!-- react-text: 30267 -->(<!-- /react-text --><!-- react-text: 30268 -->body<!-- /react-text --><!-- react-text: 30269 -->)<!-- /react-text --></div></td><td class="parameters-col_description"><div class="markdown"><p>request</p>
// </div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div class="body-param" data-param-name="request" data-param-in="body"><div class="highlight-code"><pre class="body-param__example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"password"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"username"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div><div class="body-param-options"><label for=""><span>Parameter content type</span><div class="content-type-wrapper body-param-content-type"><select class="content-type"><option value="application/json">application/json</option></select></div></label></div></div></div></div></td></tr></tbody></table></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="201"><td class="response-col_status">201</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Created</p>
// </div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30338 --> <!-- /react-text --></div></div></span><span><div class="opblock opblock-get is-open" id="operations-用户-getInfoUsingGET"><div class="opblock-summary opblock-summary-get"><span class="opblock-summary-method">GET</span><span class="opblock-summary-path" data-path="/api/user/stat"><a class="nostyle" href="#/用户/getInfoUsingGET"><span>​/api​/user​/stat</span></a></span><div class="opblock-summary-description">获取用户个人信息</div><button class="authorization__btn unlocked" aria-label="authorization button unlocked"><svg width="20" height="20"><use href="#unlocked" xlink:href="#unlocked"></use></svg></button><!-- react-empty: 24998 --></div><div class="no-margin"><!-- react-text: 30180 --> <!-- /react-text --><div class="opblock-body"><div class="opblock-section"><div class="opblock-section-header"><div class="tab-header"><h4 class="opblock-title">Parameters</h4></div><div class="try-out"><button class="btn try-out__btn">Try it out </button></div></div><div class="parameters-container"><div class="opblock-description-wrapper"><p>No parameters</p></div></div></div><div class="execute-wrapper"></div><div class="responses-wrapper"><div class="opblock-section-header"><h4>Responses</h4><label><span>Response content type</span><div class="content-type-wrapper execute-content-type"><select class="content-type"><option value="*/*">*/*</option></select></div></label></div><div class="responses-inner"><table class="responses-table"><thead><tr class="responses-header"><td class="col_header response-col_status">Code</td><td class="col_header response-col_description">Description</td></tr></thead><tbody><tr class="response " data-code="200"><td class="response-col_status">200</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>OK</p>
// </div></div><div class="model-example"><ul class="tab"><li class="tabitem active"><a class="tablinks" data-name="example">Example Value</a></li><li class="tabitem"><a class="tablinks" data-name="model">Model</a></li></ul><div><div><div class="highlight-code"><pre class="example microlight"><span class="">{</span><span class="token-not-formatted">
//   </span><span class="token-string">"code"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"currentPage"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"data"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="">{</span><span class="">}</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"message"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-string">"string"</span><span class="">,</span><span class="token-not-formatted">
//   </span><span class="token-string">"total"</span><span class="">:</span><span class="token-not-formatted"> </span><span class="token-not-formatted">0</span><span class="token-not-formatted">
// </span><span class="">}</span></pre></div></div></div></div></td></tr><tr class="response " data-code="401"><td class="response-col_status">401</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Unauthorized</p>
// </div></div></td></tr><tr class="response " data-code="403"><td class="response-col_status">403</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Forbidden</p>
// </div></div></td></tr><tr class="response " data-code="404"><td class="response-col_status">404</td><td class="response-col_description"><div class="response-col_description__inner"><div class="markdown"><p>Not Found</p>
// </div></div></td></tr></tbody></table></div></div></div><!-- react-text: 30237 --> <!-- /react-text --></div></div></span><!-- react-text: 25000 --> <!-- /react-text --></div></div></span><span><div class="opblock-tag-section"><h4 class="opblock-tag" id="operations-tag-管理员" data-tag="管理员" data-is-open="false"><a class="nostyle" href="#/管理员"><span>管理员</span></a><small><div class="markdown"><p>Admin Controller</p>
// </div></small><div></div><button class="expand-operation" title="Expand operation"><svg class="arrow" width="20" height="20"><use href="#large-arrow" xlink:href="#large-arrow"></use></svg></button></h4><noscript></noscript></div></span><span><div class="opblock-tag-section"><h4 class="opblock-tag" id="operations-tag-零部件制造商管理" data-tag="零部件制造商管理" data-is-open="false"><a class="nostyle" href="#/零部件制造商管理"><span>零部件制造商管理</span></a><small><div class="markdown"><p>Manufacturer Controller</p>
// </div></small><div></div><button class="expand-operation" title="Expand operation"><svg class="arrow" width="20" height="20"><use href="#large-arrow" xlink:href="#large-arrow"></use></svg></button></h4><noscript></noscript></div></span><span><div class="opblock-tag-section"><h4 class="opblock-tag" id="operations-tag-飞机零部件类型管理" data-tag="飞机零部件类型管理" data-is-open="false"><a class="nostyle" href="#/飞机零部件类型管理"><span>飞机零部件类型管理</span></a><small><div class="markdown"><p>Part Class Controller</p>
// </div></small><div></div><button class="expand-operation" title="Expand operation"><svg class="arrow" width="20" height="20"><use href="#large-arrow" xlink:href="#large-arrow"></use></svg></button></h4><noscript></noscript></div></span></div></section></div>
// `;

// // 解析并输出结果
// const apiDetails = handleParse(htmlText);
// for (let index = 0; index < apiDetails.length; index++) {
//   const element = apiDetails[index];
//   text.innerHTML += `<p>${JSON.stringify(element)}</p>`;
// }